name: cloudwalk_challenge
description: "A new Flutter project."
publish_to: "none"

version: 4.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
  weather:
  cities:
  cupertino_icons: ^1.0.2
  flutter_feather_icons: ^2.0.0+1
  flutter_bloc:
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  dart_code_metrics:
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  faker: ^2.1.0

flutter:
  uses-material-design: true
