name: cloudwalk_challenge
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
  weather:
  cities:
  concerts:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  dart_code_metrics: ^4.19.2
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true




