name: core
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics:
  flutter_lints: ^2.0.0
  mocktail:
  faker: ^2.1.0

flutter:
