name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:
environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.19.2
  flutter_lints: ^2.0.0
flutter:
